### ISSUE TITLE
Clarify Dart 1 vs Dart 2

### ISSUE THREAD

**Issue by pulyaevskiy** [theyakka/cumulus#1]
This sentence from the readme:

> Cumulus will probably require Dart 2.0+. Cumulus was developed on the 2.0 (pre-release) version of Dart but, for now, it probably works fine on 1.X as well.

AFAIK, it would be safe to say that Dart 2 is required at this point.`firebase_functions_interop` and other packages it depends on use the new `build_runner` system to compile with dart2js/dartdevc. `build_runner` is effectively replacing `pub build` and `pub serve` in Dart 2 (those commands were just removed from Dart 2 SDK) and explicitly states dependency on Dart 2 in its [pubspec.yaml](https://github.com/dart-lang/build/blob/master/build_runner/pubspec.yaml).

**Comment by lukef** [comment]
Good points. I copied this from another README that I did for a different library but i'll make it clear Dart 2 is required. Thanks!

**Comment by lukef** [comment]
Fixed
